name: Tube Update Workflow

# Schedule the workflow to run every 3 hours
on:
  schedule:
    - cron: '0 */3 * * *'
  # Allow manual trigger of the workflow
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_streams:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure Git user for commits
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      # Update streaming links
      - name: Update Streams
        run: |
          streams=(
            "https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g/live france24.m3u8"
            "https://www.youtube.com/channel/UCO6K_kkdP-lnSCiO3tPx7WA/live franceinfo.m3u8"
            "https://www.youtube.com/channel/UCW2QcKZiU8aUGg4yxCIditg/live euronews.m3u8"
            "https://www.youtube.com/channel/UCT67YOMntJxfRnO_9bXDpvw/live lemedia.m3u8"
            "https://www.youtube.com/channel/UC25EuGAePOPvPrUA5cmu3dQ/live africanews.m3u8"
            "https://www.youtube.com/channel/UCUaHJ0fTA-1theR8A8Polmw/live techandco.m3u8"
            "https://www.youtube.com/channel/UCJduEGukjOXzTW4jfkQ-ihw/live relaxnature.m3u8"
            "https://www.youtube.com/channel/UCcip9fzGawR1Or5G15UwFLA/live beetoonss.m3u8"
          )
          for stream in "${streams[@]}"; do
            url=${stream% *}
            file=${stream#* }
            python3 tube.py "$url" > "$file"
            sleep 15
          done

      # Stage all changes for commit
      - name: Stage Changes
        run: git add -A

      # Commit and push updates
      - name: Commit and Push Updates
        run: |
          git commit -m "Update streaming links"
          git push
